[analytic.metadata]
categories = ["detect"]
confidence = "high"
contributors = ["Tony Lambert"]
created_date = "01/07/2019"
description = "Identifies usage of Sysinternals ``procdump.exe`` to export the memory space of lsass.exe which contains sensitive credentials."
id = "1e1ef6be-12fc-11e9-8d76-4d6bb837cda4"
name = "LSASS Memory Dumping via ProcDump.exe"
os = "windows"
tags = ["atomicblue"]
tactics = ["Credential Access"]
techniques = ["T1003"]
updated_date = "01/07/2019"

[analytic]
query = '''
process where subtype.create and
  process_name == "procdump*.exe" and command_line == "*lsass*"
'''
