[analytic.metadata]
categories = ["enrich"]
confidence = "low"
contributors = ["Endgame"]
created_date = "7/26/2019"
description = "Adversaries may search local file systems and remote file shares for files containing passwords."
id = "53de420f-7618-4330-87b1-1e57bafa7da5"
name = "Searching for Passwords in Files"
os = ["macos", "linux"]
tactics = ["Credential Access"]
techniques = ["T1081"]
updated_date = "7/26/2019"

[analytic]
query = '''
process where subtype.create
  and process_name in ("cat", "grep")
  and wildcard(command_line, "*.bash_history*", "*password*", "*passwd*")
'''
