[analytic.metadata]
categories = ["detect"]
confidence = "low"
contributors = ["Endgame"]
created_date = "7/26/2019"
description = "Adversaries may search local file systems and remote file shares for files containing passwords."
id = "62b7273b-67b2-4698-95b5-f6fafabc3390"
name = "Searching for Passwords in Files"
os = ["windows"]
tactics = ["Credential Access"]
techniques = ["T1081"]
updated_date = "7/26/2019"

[analytic]
query = '''
process where subtype.create and
  process_name == "findstr.exe" and command_line == "*password*"
| unique parent_process_name, command_line
'''
