[analytic.metadata]
categories = ["detect"]
confidence = "low"
contributors = ["Endgame"]
created_date = "7/26/2019"
description = "Identifies the installation of password filter DLLs which may be used to steal credentials from LSA."
id = "ae6ae50f-69f3-4e85-bfe2-2db9d1422517"
name = "Registration of a Password Filter DLL"
os = ["windows"]
tactics = ["Credential Access"]
techniques = ["T1174"]
updated_date = "7/26/2019"

[analytic]
query = '''
registry where hive.hklm and
  registry_path == "*SYSTEM\\ControlSet*\\Control\\Lsa\\Notification Packages*"
| unique registry_path, process_path
'''
