[analytic.metadata]
categories = ["enrich"]
confidence = "low"
contributors = ["Endgame"]
created_date = "7/26/2019"
description = "Identifies attempts to execute an existing service by running a built-in Windows command."
id = "45861478-8ba3-4302-9600-1970d5d8b074"
name = "Execution of Existing Service via Command"
os = ["windows"]
tactics = ["Execution"]
techniques = ["T1035"]
updated_date = "7/26/2019"

[analytic]
query = '''
process where subtype.create and (
  process_name == "sc.exe" and command_line == "* start *" or
  process_name == "net.exe" and match(command_line, ?".*? start *[\s].*") or
  process_name == "powershell.exe" and wildcard(command_line, "*Start-Service*") or
  process_name == "wmic.exe" and wildcard(command_line, "*service*call*startservice*")
)
'''
