[analytic.metadata]
categories = ["detect"]
confidence = "medium"
contributors = ["Endgame"]
created_date = "11/30/2018"
description = "Detect regsvr32 loading a script object (scrobj)."
id = "82200c71-f3c3-4b6c-aead-9cafeab602f5"
name = "RegSvr32 Scriplet Execution"
os = ["windows"]
tactics = ["Execution"]
tags = ["atomicblue"]
techniques = ["T1117"]
updated_date = "11/30/2018"

[analytic]
query = '''
process where subtype.create and
  process_name == "regsvr32.exe" and
  wildcard(command_line, "*scrobj*", "*/i:*", "*-i:*", "*.sct*")
'''
