[analytic.metadata]
categories = ["hunt"]
confidence = "low"
contributors = ["Endgame"]
created_date = "7/26/2019"
description = "InstallUtil may be abused to bypass process whitelisting or proxy the execution of code through a trusted Windows utility."
id = "b937f762-466f-4242-a461-d68e6e4bfc5a"
name = "InstallUtil Execution"
os = ["windows"]
tactics = ["Execution", "Defense Evasion"]
techniques = ["T1118"]
updated_date = "7/26/2019"

[analytic]
query = '''
process where subtype.create and
  process_name == "installutil.exe" and
  command_line == "* *"
| unique parent_process_name, command_line
'''
