[analytic.metadata]
categories = ["enrich"]
confidence = "low"
contributors = ["Endgame"]
created_date = "7/26/2019"
description = "The trap command allows programs and shells to specify commands that will be executed upon receiving interrupt signals."
id = "3ecbba23-0d1e-4870-8b9e-016b423aebee"
name = "Trap Signals Usage"
os = ["macos", "linux"]
tactics = ["Execution", "Persistence"]
techniques = ["T1154"]
updated_date = "7/26/2019"

[analytic]
query = '''
process where subtype.create and
  process_name == "trap" and command_line == "* signals*"
'''
