[analytic.metadata]
categories = ["enrich"]
confidence = "low"
contributors = ["Endgame"]
created_date = "7/26/2019"
description = "On Linux and macOS systems, multiple methods are supported for creating pre-scheduled and periodic background jobs."
id = "01fa72dc-5ce4-443b-96f9-703edfeefa5d"
name = "Local Job Scheduling Paths"
os = ["macos", "linux"]
tactics = ["Execution", "Persistence"]
techniques = ["T1168"]
updated_date = "7/26/2019"

[analytic]
query = '''
file where wildcard(file_path, "/etc/crontab", "/etc/cron.d", "*LaunchDaemons*")
'''
