[analytic.metadata]
categories = ["enrich"]
confidence = "low"
contributors = ["Endgame"]
created_date = "7/26/2019"
description = "On Linux and macOS systems, multiple methods are supported for creating pre-scheduled and periodic background jobs."
id = "7f490015-20b2-43e3-acf7-e2f2d098505d"
name = "Local Job Scheduling Process"
os = ["macos", "linux"]
tactics = ["Execution", "Persistence"]
techniques = ["T1168"]
updated_date = "7/26/2019"

[analytic]
query = '''
process where subtype.create and
  process_name in ("cron", "at", "launchd")
'''
