[analytic.metadata]
categories = ["detect"]
confidence = "low"
contributors = ["Endgame"]
created_date = "7/26/2019"
description = "Processes should always be executing with PE extensions, such as ``.exe``, so any execution from non-PE extensions, such as ``.gif`` are immediately suspicious."
id = "251c26ff-658b-42d1-a808-bafcd4b52284"
name = "Processes Running with Unusual Extensions"
os = ["windows"]
tactics = ["Defense Evasion"]
techniques = ["T1036"]
updated_date = "7/26/2019"

[analytic]
query = '''
process where subtype.create
  and wildcard(process_name,
               "*.pif" ,  "*.pdf",    "*.docx",   "*.doc",
               "*.xlsx",  "*.xls",    "*.pptx",   "*.ppt",
               "*.txt",   "*.rtf",    "*.gif",    "*.jpg",
               "*.png",   "*.bmp",    "*.vbs",    "*.vbe",
               "*.bat",   "*.js",     "*.cmd",
               "*.wsh",   "*.ps1",    "* ",
              )
'''
