[analytic.metadata]
categories = ["detect"]
confidence = "low"
contributors = ["Endgame"]
created_date = "11/30/2018"
description = "Identifies attempts to clear Windows event logs with the command ``wevtutil``."
id = "5b223758-07d6-4100-9e11-238cfdd0fe97"
name = "Clearing Windows Event Logs with wevtutil"
os = ["windows"]
tactics = ["Defense Evasion"]
tags = ["atomicblue"]
techniques = ["T1070"]
updated_date = "11/30/2018"

[analytic]
query = '''
process where subtype.create and
  process_name == "wevtutil.exe" and command_line == "* cl *"
'''
