[analytic.metadata]
categories = ["enrich"]
confidence = "low"
contributors = ["Endgame"]
created_date = "7/26/2019"
description = "Adversaries may delete artifacts on a host system, including logs, browser history, or directories."
id = "339d4a19-dfb8-4d86-89c8-6a3ac807a57f"
name = "Host Artifact Deletion"
os = ["windows"]
tactics = ["Defense Evasion"]
techniques = ["T1070"]
updated_date = "7/26/2019"

[analytic]
query = '''
process where subtype.create and (
  (process_name == "rundll32.exe" and command_line == "*InetCpl.cpl,Clear*") or
  (process_name == "reg.exe" and command_line == "* delete *") or
  (process_name == "cmd.exe" and command_line == "* *rmdir *")
)
'''
