[analytic.metadata]
categories = ["enrich"]
confidence = "low"
contributors = ["Endgame"]
created_date = "7/26/2019"
description = "Identifies attempts to remove network shares with the Windows built-in command net.exe"
id = "7d328c61-8f63-4411-9ae7-e5b502a80e7e"
name = "Disconnecting from Network Shares with net.exe"
os = ["windows"]
tactics = ["Defense Evasion"]
techniques = ["T1126"]
updated_date = "7/26/2019"

[analytic]
query = '''
process where subtype.create and
  process_name == "net.exe" and command_line == "* /d*"
'''
