[analytic.metadata]
categories = ["detect"]
contributors = ["Endgame"]
confidence = "medium"
created_date = "11/30/2018"
description = "Find execution of the Windows tool certutil.exe to decode or encode files."
id = "c6facc54-4894-4722-b873-062baaae851f"
name = "Encoding or Decoding Files via CertUtil"
os = ["windows"]
tactics = ["Defense Evasion"]
tags = ["atomicblue"]
techniques = ["T1140"]
updated_date = "11/30/2018"

[analytic]
query = '''
process where subtype.create and
  process_name == "certutil.exe" and
  (command_line == "*encode *" or command_line == "*decode *")
'''
