[analytic.metadata]
categories = ["detect"]
confidence = "low"
contributors = ["Endgame"]
created_date = "7/26/2019"
description = "In macOS, when applications or programs are downloaded from the internet, there is a special attribute set on the file. This attribute is read by Apple's Gatekeeper defense program at execution time."
id = "a4fe6af5-bc33-4e72-8241-eea885b95c46"
name = "Potential Gatekeeper Bypass"
os = ["macos"]
tactics = ["Defense Evasion"]
techniques = ["T1144"]
updated_date = "7/26/2019"

[analytic]
query = '''
process where subtype.create and
  process_name == "xattr" and
  command_line == "*com.apple.quarantine*"
| unique command_line
'''
