[analytic.metadata]
categories = ["enrich"]
confidence = "low"
contributors = ["Endgame"]
created_date = "7/26/2019"
description = "Adversaries can add the *hidden* attribute to files to hide them from the user in an attempt to evade detection"
id = "9051814c-a142-4b1c-965b-76a09dace760"
name = "Adding the Hidden File Attribute with via attrib.exe"
os = ["windows"]
tactics = ["Defense Evasion", "Persistence"]
techniques = ["T1158"]
updated_date = "7/26/2019"

[analytic]
query = '''
process where subtype.create and
  process_name == "attrib.exe" and
  command_line == "* +h*"
'''
