[analytic.metadata]
categories = ["detect"]
confidence = "low"
contributors = ["Endgame"]
created_date = "7/26/2019"
description = "Identifies processes running with a trailing space, which can be used to look like an ordinary file while evading default file handlers."
id = "391c27cf-68d5-4416-9315-cdfde096a33b"
name = "Processes with Trailing Spaces"
os = ["macos", "linux"]
tactics = ["Defense Evasion", "Execution"]
techniques = ["T1151"]
updated_date = "7/26/2019"

[analytic]
query = '''
process where subtype.create
  and process_name == "* "
'''
