[analytic.metadata]
categories = ["detect"]
confidence = "medium"
contributors = ["Endgame"]
created_date = "11/30/2018"
description = "Detect download of BITS jobs via bitsadmin.exe."
id = "ef9fe5c0-b16f-4384-bb61-95977799a84c"
name = "Suspicious Bitsadmin Job via bitsadmin.exe"
os = ["windows"]
tactics = ["Defense Evasion", "Persistence"]
tags = ["atomicblue"]
techniques = ["T1197"]
updated_date = "11/30/2018"

[analytic]
query = '''

process where subtype.create and
  process_name == "bitsadmin.exe" and command_line == "* /download *"

'''
