[analytic.metadata]
categories = ["detect"]
confidence = "medium"
contributors = ["Dan Beavin"]
created_date = "08/08/2019"
description = "Identifies usage of hh.exe executing recently modified .chm files."
id = "b25aa548-7937-11e9-8f5c-d46d6d62a49e"
name = "HH.exe execution"
os = ["windows"]
tactics = ["Defense Evasion", "Execution"]
techniques = ["T1223"]
updated_date = "08/08/2019"

[analytic]
query = '''
sequence with maxspan=1d
   [file where file_name == "*.chm"]
   [process where subtype.create and process_name == "hh.exe" and command_line == "* *.chm*"]
'''
