[analytic.metadata]
categories = ["enrich"]
confidence = "low"
contributors = ["Endgame"]
created_date = "7/26/2019"
description = "Commands used to obtain information about the remote system."
id = "9be90e44-c0f7-4fd2-9378-be00c25a02d7"
name = "Remote System Discovery Commands"
os = ["windows"]
tactics = ["Discovery"]
techniques = ["T1018"]
updated_date = "7/26/2019"

[analytic]
query = '''
process where subtype.create and (
  process_name == "nbtstat.exe" and wildcard(command_line, "* -n*", "* -s*") or
  process_name == "arp.exe" and command_line == "* -a*"
)
'''
