[analytic.metadata]
categories = ["enrich"]
confidence = "low"
contributors = ["Endgame"]
created_date = "7/26/2019"
description = "Built-in tools can be used to enumerate and discover network environment on windows systems."
id = "3a78a9fb-3714-43fa-90ca-7cf85da5a710"
name = "Discovery of Network Environment via Built-in Tools"
os = ["windows"]
tactics = ["Discovery"]
techniques = ["T1016"]
updated_date = "7/26/2019"

[analytic]
query = '''
process where subtype.create and
  process_name in ("ipconfig.exe", "route.exe", "nbtstat.exe", "arp.exe")
| unique command_line
'''
