[analytic.metadata]
categories = ["enrich"]
confidence = "low"
contributors = ["Endgame"]
created_date = "7/26/2019"
description = "Adversaries may attempt to get a listing of network connections to or from a compromised system."
id = "df696af0-8d3f-4557-8278-d10f40ba7c07"
name = "System Network Connections Discovery"
os = ["macos", "linux"]
tactics = ["Discovery"]
techniques = ["T1049"]
updated_date = "7/26/2019"

[analytic]
query = '''
process where subtype.create and
  process_name in ("netstat", "lsof", "who", "w")
| unique command_line
'''
