[analytic.metadata]
categories = ["hunt"]
confidence = "low"
contributors = ["Endgame"]
created_date = "7/26/2019"
description = "Network Service Scanning via incoming network port scanning"
id = "4f64ef9e-ee9b-4245-a3f4-777e550ebb37"
name = "Network Service Scanning via Port"
os = ["windows", "macos", "linux"]
tactics = ["Discovery"]
techniques = ["T1046"]
updated_date = "7/26/2019"

[analytic]
query = '''
network where subtype.incoming
| unique unique_pid destination_port
| unique_count unique_pid
| filter count > 25
'''
