[analytic.metadata]
categories = ["detect"]
confidence = "low"
contributors = ["Endgame"]
created_date = "11/30/2018"
description = "Identifies enumeration of remote shares with the builtin Windows tool ``net.exe``."
id = "e61f557c-a9d0-4c25-ab5b-bbc46bb24deb"
name = "Enumeration of Remote Shares"
os = ["windows"]
tactics = ["Discovery"]
tags = ["atomicblue"]
techniques = ["T1135"]
updated_date = "11/30/2018"

[analytic]
query = '''
process where subtype.create and
  (process_name == "net.exe" or (process_name == "net1.exe" and parent_process_name != "net.exe")) and
  command_line == "* view*" and command_line == "*\\\\*"
'''
