[analytic.metadata]
categories = ["enrich"]
confidence = "low"
contributors = ["Endgame"]
created_date = "7/26/2019"
description = "Built-in tools can be used to discover running processes on an endpoint"
id = "737c7bed-364f-4b47-a0aa-763c80c8aa6c"
name = "Process Discovery via Built-In Applications"
os = ["macos", "linux"]
tactics = ["Discovery"]
techniques = ["T1057", "T1063"]
updated_date = "7/26/2019"

[analytic]
query = '''
process where subtype.create and
  (process_name in ("ps", "pstree", "htop", "pgrep") or
  match(command_line, ?".*? /proc/\d+"))
'''
