[analytic.metadata]
categories = ["enrich"]
confidence = "low"
contributors = ["Endgame"]
created_date = "7/26/2019"
description = "Attackers will enumerate running processes to gain further comprehension of the environment."
id = "555a76e1-d5fe-44b9-a6bc-d275c4c446cc"
name = "Process Discovery via Windows Tools"
os = ["windows"]
tactics = ["Discovery"]
techniques = ["T1057", "T1063"]
updated_date = "7/26/2019"

[analytic]
query = '''
process where subtype.create and (
  process_name == "tasklist.exe" and not matchLite(?".* [-/]svc", command_line) or
  process_name == "quser.exe" or
  (process_name == "powershell.exe" and command_line == "*Get-Process*")
)
'''
