[analytic.metadata]
categories = ["enrich"]
confidence = "low"
contributors = ["Endgame"]
created_date = "7/26/2019"
description = "Identify usage of known commands for discovery of local groups"
id = "cd2124cb-718d-4ecf-bc96-5571f8e3dbce"
name = "Discovery of Domain Groups"
os = ["linux", "macos"]
tactics = ["Discovery"]
techniques = ["T1069"]
updated_date = "7/26/2019"

[analytic]
query = '''
process where subtype.create and (
  process_name in ("ldapsearch", "dscacheutil") or
  process_name == "dscl" and command_line == "*-list*"
)
'''
