[analytic.metadata]
categories = ["enrich"]
confidence = "low"
contributors = ["Endgame"]
created_date = "7/26/2019"
description = "System information enumeration and discovery via built-in tools."
id = "6a1247d5-8b8a-4a5c-8d35-dd9ef220e7d1"
name = "Enumeration of System Information"
os = ["linux"]
tactics = ["Discovery"]
techniques = ["T1082"]
updated_date = "7/26/2019"

[analytic]
query = '''
process where subtype.create and (
  process_name == "uname" or (
  process_name in ("cat", "more", "less") and
    wildcard(command_line,
             "* /etc/issue*",    "* /proc/version*", "* /etc/profile*", 
             "* /etc/services*", "* /proc/cpuinfo*",)
  ))
'''
