[analytic.metadata]
categories = ["hunt"]
confidence = "medium"
contributors = ["Endgame"]
created_date = "11/30/2018"
description = "Detect enumeration of Windows system information via ``systeminfo.exe``"
id = "4b9c2df7-87e2-4bbc-9123-9779ecb2dbf2"
name = "System Information Discovery"
os = ["windows"]
tactics = ["Discovery"]
tags = ["atomicblue"]
techniques = ["T1082"]
updated_date = "11/30/2018"

[analytic]
query = '''
process where subtype.create and process_name == "systeminfo.exe"
| unique user_name, command_line
'''
