[analytic.metadata]
categories = ["detect"]
confidence = "low"
contributors = ["Endgame"]
created_date = "11/30/2018"
description = "Identifies enumeration of local shares with the built-in Windows tool ``net.exe``."
id = "bc1944cd-97fc-4b9a-b068-46203b6bbcde"
name = "Enumeration of Local Shares"
os = ["windows"]
tactics = ["Discovery"]
tags = [] # Atomic Red tests don't check for the share command yet
techniques = ["T1135"]
updated_date = "11/30/2018"

[analytic]
query = '''
process where subtype.create and
  (process_name == "net.exe" or (process_name == "net1.exe" and parent_process_name != "net.exe")) and
  command_line == "* share*" and command_line != "* * *"
'''
