[analytic.metadata]
categories = ["enrich"]
confidence = "low"
contributors = ["Endgame"]
created_date = "7/26/2019"
description = "Identifies enumeration of local or global password policies using built-in commands."
id = "94a5cbe1-851a-4b8f-bd9c-04c62097ae5e"
name = "Password Policy Enumeration"
os = ["linux"]
tactics = ["Discovery"]
techniques = ["T1201"]
updated_date = "7/26/2019"

[analytic]
query = '''
process where subtype.create and (
  process_name == "chage" and command_line == "* -l *" or
  process_name == "cat" and command_line == "*/etc/pam.d/common-password*"
)
'''
