[analytic.metadata]
categories = ["enrich"]
confidence = "low"
contributors = ["Endgame"]
created_date = "7/26/2019"
description = "Detect commands used to enumerate a list of trusted domains."
id = "bccb1c48-305c-4b1f-affb-a7a50bf4654b"
name = "Domain Trust Discovery"
os = ["windows"]
tactics = ["Discovery"]
techniques = ["T1482"]
updated_date = "7/26/2019"

[analytic]
query = '''
process where subtype.create and (
  (process_name == "dsquery.exe") and command_line == "*(objectClass=trustedDomain)*" or
  (process_name == "nltest.exe") and command_line == "*domain_trusts*"
)
'''
