[analytic.metadata]
categories = ["hunt"]
confidence = "low"
contributors = ["Endgame"]
created_date = "7/26/2019"
description = "A winlogon registry key was modified to establish persistence."
id = "46de6f8f-e30e-45f7-a136-7ab140c9af08"
name = "Registration of Winlogon Helper DLL"
os = ["windows"]
tactics = ["Persistence"]
techniques = ["T1004"]
updated_date = "7/26/2019"

[analytic]
query = '''
registry where
  wildcard(registry_path,
           "*\\Software[Wow6432Node]Microsoft\\Windows NT\\CurrentVersion\\Winlogon\\*",
           "*\\Software\\Microsoft\\Windows NT\\CurrentVersion\\Winlogon\\*")
'''
