[analytic.metadata]
categories = ["hunt"]
confidence = "low"
contributors = ["Endgame"]
created_date = "7/26/2019"
description = "Identifies usage of the sc.exe command to modify existing services."
id = "15c17f6b-29c5-43a4-8adc-d298f2c4c141"
name = "Service Path Modification with sc.exe"
os = ["windows"]
tactics = ["Persistence"]
techniques = ["T1031"]
updated_date = "7/26/2019"

[analytic]
query = '''
process where subtype.create and
  process_name == "sc.exe" and
  wildcard(command_line, "* config *", "*binPath*")
'''
