[analytic.metadata]
categories = ["enrich"]
confidence = "low"
contributors = ["Endgame"]
created_date = "7/26/2019"
description = 'Adversaries can establish persistence by adding an entry to the "run keys" in the registry or startup folder. The referenced program will be executed when a user logs in.'
id = "c457d0c5-3ec8-4e9e-93f5-6ddcbfeec498"
name = "Registry Persistence via Run Keys"
os = ["windows"]
tactics = ["Persistence"]
techniques = ["T1060"]
updated_date = "7/26/2019"

[analytic]
query = '''
registry where
  registry_path == "*\\Software\\Microsoft\\Windows\\CurrentVersion\\Run*"
'''
