[analytic.metadata]
categories = ["detect"]
confidence = "low"
contributors = ["Endgame"]
created_date = "7/22/2019"
description = 'Adversaries can establish persistence by adding an entry to the "run keys" in the registry or startup folder. The referenced program will be executed when a user logs in.'
id = "f8b1720c-7116-4ec3-b38a-402f984e4972"
name = "Registry Persistence via Shell Folders"
os = ["windows"]
tactics = ["Persistence"]
tags = ["enrichment"]
techniques = ["T1060"]
updated_date = "7/22/2019"

[analytic]
query = '''
registry where
  registry_path == "\\Software\\Microsoft\\Windows\\CurrentVersion\\Explorer\\*Shell Folders*"
'''
