[analytic.metadata]
categories = ["enrich"]
confidence = "low"
contributors = ["Endgame"]
created_date = "7/26/2019"
description = "Adversaries can establish persistence by modifying registry keys related to the Windows Security Support Provider (SSP) configuration"
id = "43cfcfb8-e52d-4c1a-a110-3aecc09e6206"
name = "Installation of Security Support Provider"
os = ["windows"]
tactics = ["Persistence"]
techniques = ["T1101"]
updated_date = "7/26/2019"

[analytic]
query = '''
registry where
   wildcard(registry_path,
            "*\\SYSTEM\\CurrentControlSet\\Control\\Lsa\\Security Packages*",
            "*\\SYSTEM\\CurrentControlSet\\Control\\Lsa\\OSConfig\\Security Packages*")
'''
