[analytic.metadata]
categories = ["enrich"]
confidence = "low"
contributors = ["Endgame"]
created_date = "7/26/2019"
description = "Adversaries can modify Microsoft Office-related registry keys to establish persistence."
id = "100e0ff0-fae0-4dc0-998d-c168d7e4dcb7"
name = "Office Application Startup via Template Registry Modification"
os = ["windows"]
tactics = ["Persistence"]
techniques = ["T1137"]
updated_date = "7/26/2019"

[analytic]
query = '''
registry where wildcard(registry_path,
  "*\\Software\\Microsoft\\Office\\*\\Outlook\\Today\\UserDefinedUrl",
  "*\\Software\\Microsoft\\Office\\*\\Excel\\Options\\Open",
  "*\\Software\\Microsoft\\Office\\*\\PowerPoint\\AddIns",
  "*\\Software\\Microsoft\\Office\\*\\Addins\\*",
  "*\\SOFTWARE\\Microsoft\\Office\\*\\Excel\\Options",
  "*\\Software\\Microsoft\\VBA\\VBE\\*\\Addins\\*")
'''
