[analytic.metadata]
categories = ["detect"]
confidence = "low"
contributors = ["Tony Lambert"]
created_date = "01/10/2019"
description = 'Detect modification of .bash_profile and .bashrc files for persistent commands'
id = "3567621a-1564-11e9-8e67-d46d6d62a49e"
name = "Modifications of .bash_profile and .bashrc"
os = ["linux", "macos"]
tactics = ["Persistence"]
tags = ["atomicblue"]
techniques = ["T1156"]
updated_date = "01/10/2019"

[analytic]
query = '''
file where subtype.modify and 
  (file_name == ".bash_profile" or file_name == ".bashrc")
'''
