[analytic.metadata]
categories = ["enrich"]
confidence = "low"
contributors = ["Endgame"]
created_date = "7/26/2019"
description = "An adversary can establish persistence by installing a new launch agent that executes at login by using launchd or launchctl to load a plist into the appropriate directories"
id = "8b3a3f3b-f4f0-4cd4-82f4-28f79a3cf95b"
name = "Persistent process via Launch Agent"
os = ["macos"]
tactics = ["Persistence"]
techniques = ["T1159"]
updated_date = "7/26/2019"

[analytic]
query = '''
file where not subtype.delete and
  file_path == "*/library/launchagents/*"
'''
