[analytic.metadata]
categories = ["enrich"]
confidence = "low"
contributors = ["Endgame"]
created_date = "7/26/2019"
description = "Starting in Mac OS X 10.7 (Lion), users can specify certain applications to be re-opened when a user reboots their machine."
id = "491db9c2-8b06-4076-8f9b-de44b9bae8d0"
name = "Resumed Application on Reboot"
os = ["macos"]
tactics = ["Persistence"]
techniques = ["T1164"]
updated_date = "7/26/2019"

[analytic]
query = '''
file where file_name == "*Library/Preferences/com.apple.loginwindow.*plist"
'''
