[analytic.metadata]
categories = ["enrich"]
confidence = "low"
contributors = ["Endgame"]
created_date = "7/26/2019"
description = "Malicious browser extensions can be installed via app store downloads masquerading as legitimate extensions, social engineering, or by an adversary that has already compromised a system"
id = "7797d204-3205-4033-bac7-658fc203198d"
name = "Suspicious File Creation via Browser Extensions"
os = ["macos", "windows"]
tactics = ["Persistence"]
techniques = ["T1176"]
updated_date = "7/26/2019"

[analytic]
query = '''
file where not subtype.delete and
  wildcard(file_name, "*.exe", "*.dll", "*.ps1", "*.vbs", "*.bat") and  
  wildcard(file_path,
	   // windows
	   "*\\AppData\\Local\\Google\\Chrome\\User Data\\Default\\Extensions",
	   "*:\\Program Files\\Mozilla Firefox\\plugins\\*",
	   "*:\\Program Files\\Internet Explorer\\Plugins\\*",

	   // macos
	   "/Applications/Firefox.app/Contents/MacOS/firefox/plugins/*",
	   "/Users/*/Library/Safari/Extensions/*",
	   "/Users/*/Library/Application Support/Google/Chrome/Default/Extensions/*"
	   )
'''
