[analytic.metadata]
categories = ["enrich"]
confidence = "low"
contributors = ["Endgame"]
created_date = "7/26/2019"
description = "Attackers may establish persistence by registering a DLL with Windows as a valid time provider."
id = "3056a14a-59d9-43d3-84b5-738b4b8c3dd7"
name = "Installation of Time Providers"
os = ["windows"]
tactics = ["Persistence"]
techniques = ["T1209"]
updated_date = "7/26/2019"

[analytic]
query = '''
registry where
  registry_path == "*\\System\\CurrentControlSet\\Services\\W32Time\\TimeProviders\\*"
'''
