[analytic.metadata]
categories = ["hunt"]
confidence = "low"
contributors = ["Endgame"]
created_date = "7/26/2019"
description = "Identify activity related to loading kernel modules on MacOS via the kextload command"
id = "deca3ab9-93f2-4e1e-b782-97863bc26089"
name = "Loading Kernel Modules with kextload"
os = ["macos"]
tactics = ["Persistence"]
techniques = ["T1215"]
updated_date = "7/26/2019"

[analytic]
query = '''
process where subtype.create and
  process_name == "kextload"
'''
