[analytic.metadata]
categories = ["enrich"]
confidence = "low"
contributors = ["Endgame"]
created_date = "7/26/2019"
description = "Identify activity related to loading kernel modules on Linux via creation of new ko files in the LKM directory"
id = "9e711823-72f1-4c5c-843d-9afc90c4e6a1"
name = "Creation of Kernel Module"
os = ["linux"]
tactics = ["Persistence"]
techniques = ["T1215"]
updated_date = "7/26/2019"

[analytic]
query = '''
file where subtype.create and 
  file_path == "/lib/modules/*" and file_name == "*.ko"
'''
