[analytic.metadata]
categories = ["enrich"]
confidence = "low"
contributors = ["Endgame"]
created_date = "7/26/2019"
description = "Systemd services can be used to establish persistence on a Linux system. The systemd service manager is commonly used for managing background daemon processes (also known as services) and other system resources."
id = "1a568233-9ca1-4c2c-b2e7-b15b90e2c954"
name = "Creation or Modification of Systemd Service"
os = ["linux"]
tactics = ["Persistence"]
techniques = ["T1501"]
updated_date = "7/26/2019"

[analytic]
query = '''
file where not subtype.delete and
  file_name == "*.service*" and
  wildcard(file_path, "/etc/systemd/system/*","/usr/lib/systemd/system/*")
'''
