[analytic.metadata]
categories = ["enrich"]
confidence = "low"
contributors = ["Endgame"]
created_date = "7/26/2019"
description = "Detects when running services are stopped with the net.exe command."
id = "0b2ea078-b2ef-4cf7-aef1-564a63662e3b"
name = "Stopping Services with net.exe"
os = ["windows"]
tactics = ["Impact"]
techniques = ["T1489"]
updated_date = "7/26/2019"

[analytic]
query = '''
process where subtype.create and
  process_name == "net.exe" and
  command_line == "* stop *"
'''
