[analytic.metadata]
categories = ["enrich"]
confidence = "low"
contributors = ["Endgame"]
created_date = "7/26/2019"
description = "Detects when running services are stopped with the sc.exe command"
id = "591da84a-0382-40e7-afc8-12bd58c40425"
name = "Service Stop or Disable with sc.exe"
os = ["windows"]
tactics = ["Impact"]
techniques = ["T1489"]
updated_date = "7/26/2019"

[analytic]
query = '''
process where subtype.create and
  process_name == "sc.exe" and
  wildcard(command_line, "* stop*", "* config *disabled*")
'''
