[analytic.metadata]
categories = ["enrich"]
confidence = "low"
contributors = ["Endgame"]
created_date = "7/26/2019"
description = "Incoming lateral movement via Windows Remote Management (WinRM)"
id = "3abf86e1-3ba3-4473-90ea-5fc37ff57d18"
name = "Incoming Remote PowerShell Sessions"
os = ["windows"]
tactics = ["Lateral Movement", "Execution"]
techniques = ["T1028"]
updated_date = "7/26/2019"

[analytic]
query = '''
sequence with maxspan=2s
  [network where subtype.incoming and destination_port in (5985, 5986)]
  [process where subtype.create and
    process_name == "wsmprovhost.exe" and parent_process_name == "svchost.exe"]
'''
