[analytic.metadata]
categories = ["hunt"]
confidence = "low"
contributors = ["Endgame"]
created_date = "7/26/2019"
description = "Identifies possible Remote Desktop Protocol session hijacking"
id = "46ff4da0-2f55-4023-8de3-1709fbd33f1d"
name = "Remote Desktop Protocol Hijack"
os = ["windows"]
tactics = ["Lateral Movement"]
techniques = ["T1076"]
updated_date = "7/26/2019"

[analytic]
query = '''
process where subtype.create and
  process_name == "tscon.exe" and command_line == "* *"
'''
