[analytic.metadata]
categories = ["hunt"]
confidence = "low"
contributors = ["Endgame"]
created_date = "7/26/2019"
description = "Identifies hidden Windows Admin Network shares"
id = "8e7c9bce-565b-4ee1-bb70-37dc61afc8d0"
name = "Mounting Windows Hidden Shares with net.exe"
os = ["windows"]
tactics = ["Lateral Movement"]
techniques = ["T1077"]
updated_date = "7/26/2019"

[analytic]
query = '''
process where subtype.create and
  (process_name == "net.exe" or (process_name == "net1.exe" and parent_process_name != "net.exe")) and
  (command_line == "* use \\\\*\\*$*" or command_line == "* use \\\\*/*$*")
'''
