[analytic.metadata]
categories = ["enrich"]
confidence = "low"
contributors = ["Endgame"]
created_date = "7/26/2019"
description = "Adversaries may collect and stage data in a central location or directory in preparation of exfiltration"
id = "f43f66f3-7e86-4cd1-9850-df7b4ac7822e"
name = "Creation of an Archive with Common Archivers"
os = ["macos", "linux"]
tactics = ["Collection"]
techniques = ["T1074"]
updated_date = "7/26/2019"

[analytic]
query = '''
sequence by unique_pid with maxspan=1m
  [ process where subtype.create and process_name in ("zip", "tar", "gzip", "hdiutil") ]
  [ file where wildcard(file_name, "*.zip", "*.tar", "*.gzip", "*.gz") ]
'''
