[analytic.metadata]
categories = ["enrich"]
confidence = "low"
contributors = ["Endgame"]
created_date = "7/26/2019"
description = "Adversaries may collect data stored in the clipboard from users copying information within or between applications."
id = "4e026838-f673-4a5b-b380-615d624fbd00"
name = "Reading the Clipboard with pbpaste"
os = ["macos"]
tactics = ["Collection"]
techniques = ["T1115"]
updated_date = "7/26/2019"

[analytic]
query = '''
process where subtype.create and process_name == "pbpaste"
'''
