[analytic.metadata]
categories = ["enrich"]
confidence = "low"
contributors = ["Endgame"]
created_date = "7/26/2019"
description = "Collection of sensitive information via .ost and .pst outlook archive files."
id = "15d87029-42c1-4992-a49b-aac74d451c06"
name = "Access of Outlook Email Archives"
os = ["windows"]
tactics = ["Collection"]
techniques = ["T1114"]
updated_date = "7/26/2019"

[analytic]
query = '''
process where subtype.create and wildcard(command_line, "*.ost *", "*.pst *")
'''
