[analytic.metadata]
categories = ["detect"]
confidence = "medium"
contributors = ["Endgame"]
created_date = "11/30/2018"
description = "Detect attacker collecting audio via PowerShell Cmdlet."
id = "ab7a6ef4-0983-4275-a4f1-5c6bd3c31c23"
name = "Audio Capture via PowerShell"
os = ["windows"]
tactics = ["Collection"]
tags = ["atomicblue"]
techniques = ["T1123"]
updated_date = "11/30/2018"

[analytic]
query = '''
process where subtype.create and
  process_name == "powershell.exe" and command_line == "* WindowsAudioDevice-Powershell-Cmdlet *"

'''
