[analytic.metadata]
categories = ["detect"]
confidence = "medium"
contributors = ["Endgame"]
created_date = "11/30/2018"
description = "Detect audio collection via SoundRecorder application."
id = "f72a98cb-7b3d-4100-99c3-a138b6e9ff6e"
name = "Audio Capture via SoundRecorder"
os = ["windows"]
tactics = ["Collection"]
tags = ["atomicblue"]
techniques = ["T1123"]
updated_date = "11/30/2018"

[analytic]
query = '''
process where subtype.create and
  process_name == "SoundRecorder.exe" and command_line == "* /FILE*"

'''
