[analytic.metadata]
categories = ["hunt"]
confidence = "low"
contributors = ["Endgame"]
created_date = "7/26/2019"
description = "A port monitors can be registered by calling the ``AddMonitor`` API with a path to a DLL. This functionality can be abused by attackers to establish persistence."
id = "dce405ba-0f30-4278-b6c6-80d57847ba6b"
name = "Installation of Port Monitor"
os = ["windows"]
tactics = ["Privilege Escalation", "Persistence"]
techniques = ["T1013"]
updated_date = "7/26/2019"

[analytic]
query = '''
registry where registry_path == "*ControlSet*\\Control\\Print\\Monitors*"
'''
