[analytic.metadata]
categories = ["hunt"]
confidence = "low"
contributors = ["Endgame"]
created_date = "7/26/2019"
description = "A scheduled task can be used by an adversary to establish persistence, move laterally, and/or escalate privileges. "
id = "9583c2ff-508d-4ebb-8b89-712b0a4d3186"
name = "Creation of Scheduled Task with schtasks.exe"
os = ["windows"]
tactics = ["Privilege Escalation", "Execution", "Persistence"]
techniques = ["T1053"]
updated_date = "7/26/2019"

[analytic]
query = '''
process where subtype.create and
  process_name = "schtasks.exe" and
  command_line = "*create*"
'''
