[analytic.metadata]
categories = ["detect"]
confidence = "high"
contributors = ["Tony Lambert"]
created_date = "05/17/2019"
description = "Identifies use of WSReset.exe to bypass User Account Control. Adversaries use this technique to execute privileged processes."
id = "532b5ed4-7930-11e9-8f5c-d46d6d62a49e"
name = "Bypass UAC via WSReset.exe"
os = ["windows"]
references = []
tactics = ["Privilege Escalation"]
tags = ["atomicblue"]
techniques = ["T1088"]
updated_date = "05/17/2019"

[analytic]
query = '''
process where subtype.create and
  parent_process_name == "wsreset.exe" and process_name != "conhost.exe"
'''
