[analytic.metadata]
categories = ["enrich"]
confidence = "low"
contributors = ["Endgame"]
created_date = "7/26/2019"
description = "An adversary can maintain persistence by installing a new launch daemon that can be configured to execute upon startup"
id = "24cb8b7c-92fe-4d62-af0e-d3de993cd48b"
name = "Launch Daemon Persistence"
os = ["macos"]
tactics = ["Privilege Escalation", "Persistence"]
techniques = ["T1160"]
updated_date = "7/26/2019"

[analytic]
query = '''
 process where subtype.create and
   parent_process_name == "launchd"
'''
